name: CI (Jira cloud example with GH action - demo)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'  
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn clean compile test --file pom.xml
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: bld-output
        path: target/
        
    - name: Submit results to Xray
      uses: mikepenz/xray-action@v0.9.4
      with:
        username: ${{ secrets.XRAY_CLIENT_ID }}
        password: ${{ secrets.XRAY_CLIENT_SECRET }}
        testFormat: "junit"
        testPaths: "**/surefire-reports/*.xml"
        projectKey: "MJP"
